Add dags for druid ingestion and run it on kubernets cluster
f-lab-edu/music-stream-data-pipeline pull request #31
Opened 2023-09-16 13:39 UTC by jieun1128

- druid를 kubernetes 상에 배포
- ingestion spec을 담은 json파일들을 druid_application 폴더에 위치
- Airflow상에서 Druid operator를 이용하여 kubernetes cluster상의 router에 ingestion 요청을 보내도록 구현

@f-lab-daniel 리뷰 부탁드립니다!

2023-09-22 22:08 UTC, f-lab-daniel requested changes
@jieun1128 
1. Druid 스키마 정의할때 Dimension은 비트맵인덱싱으로 저장되므로 카디널리티가 높은 컬럼들은 Dimension으로 정의되면 안됩니다.
2. metric설정이 안보이는데, 수치값들은 모두 메트릭으로 설정하고, count 항목도 테이블별로 추가해주세요

위 내용을 적용한 이후와 이전의 쿼리 응답 성능을 비교해서 개선점으로 어필해도 좋을것같아요.

2023-10-23 11:49 UTC, jieun1128 commented
@f-lab-daniel 수정 완료했습니다! 확인 부탁드립니다

2023-10-25 14:26 UTC, f-lab-daniel commented on airflow/dags/spark_application/listen_join.yaml
> +  arguments: ["listen", {{var.value.get("bucket_name")}},  {{yesterday_ds}}, {{var.value.get("obj_public_key")}}, {{var.value.get("obj_secret_key")}}, {{var.value.get("endpoint_url")}},  {{var.value.
ds를 그대로 사용하면, Daily 스케줄인 경우 Airflow에서 자동으로 어제 일자의 date_id가 입력되는데, yesterday_ds를 사용한 이유가 있나요?

2023-10-25 14:40 UTC, f-lab-daniel requested changes
@jieun1128  리뷰가 늦어져서 죄송합니다! 확인 부탁해요~

2023-10-25 14:40 UTC, f-lab-daniel commented on airflow/dags/spark_application/listen_join.yaml
> +    memory: "1024m"
Airflow DAG코드에서 Spark 실행 리소스를 파라메터로 전달할수 있는 방법은 없을까요?

2023-10-25 14:40 UTC, f-lab-daniel commented on spark/silver/event_processors.py
> +                "success",
여기서는 목적이 분단위로 집계하는거죠? 그렇다면 groupBy("min") 만 사용하고, 나머지 메트릭 컬럼들에 대해 집계 함수(mean, max, min, last 등) 가 정의되어있어야해요.

2023-10-25 14:40 UTC, f-lab-daniel commented on spark/silver/event_processors.py
> +                "min",
ditto

2023-10-25 14:40 UTC, f-lab-daniel commented on spark/silver/event_processors.py
> +                "min",
ditto

2023-10-25 14:40 UTC, f-lab-daniel commented on spark/silver/event_processors.py
> +                "min",
ditto

2023-10-25 14:40 UTC, f-lab-daniel commented on spark/silver/event_processors.py
> +                "success",
Spark에서 groupBy는 굉장히 많은 셔플(wide dependancy)를 발생시키는데요
만약 분단위로 집계하는게 아니라 event단위로 event_count만 붙이고 싶은것이라면, 여기서 groupBy를 사용해서 event_count컬럼을 붙이는 대신, Druid의 ingesion spec에 count 타입을 사용해서 모든 row에 1을 붙여줘서 count를 집계할 수 있어요.
(https://druid.apache.org/docs/latest/querying/aggregations/#count-aggregator)

2023-10-26 10:25 UTC, jieun1128 commented on airflow/dags/spark_application/listen_join.yaml
> +  arguments: ["listen", {{var.value.get("bucket_name")}},  {{yesterday_ds}}, {{var.value.get("obj_public_key")}}, {{var.value.get("obj_secret_key")}}, {{var.value.get("endpoint_url")}},  {{var.value.
10월 26일자의 이벤트 데이터는 그 다음날인 10월 27에 처리하게 되는데 raw 데이터가 생성될때 10월 26일(어제의 날짜)이라고 저장되거든요. 불러올때는 어제자의 날짜 기준으로 불러오고, 처리하고 나서부터는 오늘 날짜로 저장되서 오늘 일자로 불러오게 해두었어요.

2023-10-26 10:31 UTC, jieun1128 commented on airflow/dags/spark_application/listen_join.yaml
> +    memory: "1024m"
K8s의 custom resource인 SparkApplication type으로 모든 파라미터를 yml파일에 작성해서 보내주도록 되어있고, SparkKubernetesOperator 상에 실행 리소스를 지정하는 파라미터는 없어요. 만약 그렇게 하려면 SparkSubmitOperator를 이용하도록 다시 바꿔야 할 것 같습니다.

2023-10-26 10:34 UTC, jieun1128 commented on spark/silver/event_processors.py
> +                "success",
@f-lab-daniel 그러면 spark 단계에서 집계를 수행하지 않고 druid에서 바로 집계를 진행하도록 수정하는게 낫다는 말씀이신건가요???

2023-10-27 13:08 UTC, f-lab-daniel commented on spark/silver/event_processors.py
> +                "success",
@jieun1128  만약 분단위 집계를 한다면 Spark에서 하는게 효율적일수 있어요. 하지만 단순히 count 필드를 붙여주는것이라면 Druid의 count aggregator를 사용하는것이 좋다는 의미였습니다~

2023-10-27 13:10 UTC, f-lab-daniel commented on airflow/dags/spark_application/listen_join.yaml
> +    memory: "1024m"
아 그렇군요~ 저는 AWS의 EMROperator를 사용하는데, SparkConfig를 DAG에서 전달할 수 있어서 좋은것같아요. 
다음에 기회가 되면 AWS EMR로도 Spark 프로젝트를 해보는것도 추천드려요

2023-10-27 13:12 UTC, f-lab-daniel approved these changes
확인했습니다. LGTM!

2023-10-28 06:02 UTC, merged